### ISSUE TITLE
Need update for new "South Sudan Standard Time"

### ISSUE THREAD

**Issue by mattjohnsonpint** [tomkludy/TimeZoneWindowsResourceExtractor#2]
There's a new Windows time zone "South Sudan Standard Time" released with the 2021-03-29 builds of Windows.

Would you please re-run the extractor and update the json file accordingly?

Thanks.

**Comment by tomkludy** [comment]
Hi @mattjohnsonpint, I fully updated my Windows Server 2019 VM and re-ran the tool on it, then uploaded the tzinfo.json file.  The "South Sudan Standard Time" time zone was picked up.  However, all of the languages that you had added in your last PR were not found on the system and were therefore deleted.

The 38 languages found during my run match the 38 languages that Microsoft lists as supported by language packs.  I don't know where the other languages came from on your run of the tool?  Perhaps this is a difference between Windows Server and Windows 10?  Although even Win10 seems to only have 38 supported languages?

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows#language-packs

Since I can't replicate those other languages from my system and the count of 38 languages seems logical, the new file is checked in.  Thank you for bringing my attention to this, and let me know if there is anything else I can help with!

**Comment by tomkludy** [comment]
BTW - if you do need the other language entries, unfortunately since I can't replicate them with my system, you can submit a PR and I will review & accept.  Thanks!
